service: yt-videos
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  profile: pc_serverless
  stage: ${opt:stage, 'dev'}
  timeout: 300
  environment:
    FOO: bar

functions:
  list:
    handler: handler.getChannelVideos
    events:
      - http: 
          path: list
          method: get
          cors: true
    layers:
      - { Ref: ChromiumLambdaLayer }

layers:
  chromium:
    path: layers
