service: yt-videos
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  profile: pc_serverless
  stage: dev
  environment:
    FOO: bar

functions:
  list:
    handler: handler.getChannelVideos
    events:
      - http: 
          path: list
          method: get
          cors: true    
